### PR TITLE
fix issue with incorrect highlighting and character replacement on ch…

### PR DESCRIPTION
**Pull request by szweier**
…inese keyboard

### CODE REVIEW

**Comment by Ferrick90** [comment]
@szweier PRs Looks good. But defaultAttributes and mentionAttributes got some issue.

12659608_10205773470206515_1259942065_n

I think defaultAttributes and mentionsAttributes should apply same font type and font size.

**Comment by szweier** [comment]
If you set a font for mention attributes you should also be sure to set a font for default attributes so it changes back. Was the example shown running my example or are these changes you made.

**Comment by szweier** [comment]
If this is happening with changes you've made can you submit a PR with the setup. If not I'll check tomorrow to see why the font wouldn't be changing back. Currently I'm not sure why this would happen outside of not specifying a default font. My intention was to allow for the default and mentions attributes to be highly customizable. I could potentially add a check that would issue an alert or some sort of warning if you provided an attribute for either default or mention attributes that do not exist on both. That warning should allow for anyone using the library to know that what you've shown above could happen.

**Comment by szweier** [comment]
I'll work on the other issue mentioned here in a new PR

**Pull request merged**
